language: php

matrix:
    include:
        - php: 5.5
        - php: 5.6
        - php: 7.0
    allow_failures:
        - php: 7.0
    fast_finish: true
    
install:
  - sudo apt-get install nginx
  - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
  - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
  - sudo cp -f .travis_nginx.conf /etc/nginx/sites-enabled/default.conf
  - sudo sed -e "s?%APP_DIR%?$(pwd)/features/application?g" --in-place /etc/nginx/sites-enabled/default.conf
  - sudo service nginx restart

before_script:
  - composer self-update && composer --dev install

script:
  - ./bin/phpspec run -f pretty
  - ./bin/behat --profile=ci --format=progress

